# ========================
# STAGE 1: build / checks
# ========================
FROM node:22.19.0 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run format:check
RUN npm run lint
RUN npm run test
RUN npm run build


# ========================
# STAGE 2: production
# ========================
FROM node:22.19.0

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["node", "dist/main"]
